theme = "gruber"

[editor]
line-number = "relative"

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal]
C-u = ["half_page_up", "goto_window_center"]
C-d = ["half_page_down", "goto_window_center"]
C-r = ":config-reload"
x = ["extend_line_below", "select_mode"]
X = ["extend_line_up", "extend_to_line_bounds", "select_mode"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
esc = ["collapse_selection", "keep_primary_selection"]
"space" = { "w" = { "b" = ":write" } }
C-h = ["select_prev_sibling", "extend_to_line_bounds"]
C-l = ["select_next_sibling", "extend_to_line_bounds"]
C-k = ["expand_selection", "extend_to_line_bounds"]
C-j = ["shrink_selection", "extend_to_line_bounds"]
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
C = ["collapse_selection", "extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["collapse_selection", "extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
"A-d" = "copy_selection_on_prev_line"
"A-c" = "copy_selection_on_next_line"
c = ["yank_main_selection_to_clipboard", "change_selection"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "collapse_selection"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
y = ["yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
c = ["yank_main_selection_to_clipboard", "change_selection"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
p = "replace_selections_with_clipboard"
P = "paste_clipboard_before"
C-h = ["select_prev_sibling", "extend_to_line_bounds"]
C-l = ["select_next_sibling", "extend_to_line_bounds"]
C-k = ["expand_selection", "extend_to_line_bounds"]
C-j = ["shrink_selection", "extend_to_line_bounds"]
x = ["extend_line_below", "select_mode"]
X = ["extend_line_up", "extend_to_line_bounds"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"A-d" = "copy_selection_on_prev_line"
"A-c" = "copy_selection_on_next_line"
